Lcam-382
ministryofjustice/laa-crown-court-contribution pull request #50
Opened 2023-06-12 19:52 UTC by loganathanMOJ

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-382)

Describe what you did and why.

Migrate check_contribs_conditions store procedure 

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2023-06-13 16:26 UTC, muthusubra approved these changes

2023-06-14 06:55 UTC, venkat980 requested changes
Overall great work, can we add 3 more tests to cover the missed conditions to make it 100% please?

2023-06-14 06:55 UTC, venkat980 commented on crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/repository/CorrespondenceRuleRepository.java
> +    @Query(value = "SELECT R.CALC_CONTRIBS, R.UPLIFT_COTE_ID, R.REASSESSMENT_COTE_ID, T.ID, T.COTY_CORRESPONDENCE_TYPE, T.DESCRIPTION " +
Any reason why we are using native query here?

2023-06-14 08:31 UTC, muthusubra approved these changes

2023-06-15 07:22 UTC, venkat980 approved these changes

2023-06-15 08:28 UTC, merged